# Site settings
timezone: America/New_York
encoding: UTF-8
lang: fr-FR
locale: fr-FR
branch: gh-pages
future: true

title: Fred Nagorny
title_separator : "-"
tagline: "animation shorts and making of"
description: "An animation professor portfolio."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://frednagorny.fr" # the base hostname & protocol for your site
author: Fred Nagorny
# picture: "/assets/images/logo.jpg"

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:
youtube_url: "https://www.youtube.com/channel/UCXQk9hrbllT5By2MwLcuSQA"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Plugins (previously gems:)
plugins:
  # - jekyll-paginate
  - jekyll-sitemap
  # - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  # - jekyll-redirect-from
  - jekyll-seo-tag

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-seo-tag

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  # ignore:
  #   envs: development

# SEO
repository: a1rb4ck/fred_website
logo: "/assets/images/logo.jpg"
social:
  links: "https://www.youtube.com/channel/UCXQk9hrbllT5By2MwLcuSQA"
defaults:
  - scope:
      path: ""
    values:
      image: "/assets/images/logo.jpg"
