# Site settings
title: Fred Nagorny
description: An animation professor portfolio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Fred Nagorny

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:
youtube_url: https://www.youtube.com/channel/UCXQk9hrbllT5By2MwLcuSQA

# Build settings
markdown: kramdown
